services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib.postgresql/data
    networks:
      - spring-network
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_DDL_AUTO: update
    networks:
      - spring-network
volumes:
  pg_data:

networks:
  spring-network: